spring.application.name=optilock-ticketing

spring.datasource.url=jdbc:postgresql://localhost:5432/optilock_db
spring.datasource.username=anweshaarya
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=c2FtcGxlLWRldi1vbmx5LXNlY3JldC1kby1ub3QtdXNlLWluLXByb2Q=
app.jwt.expiration-ms=3600000